version: '3.1'

services:
  crawler-mongodb:
    container_name: onecrawl-db
    image: mongo
    ports:
      - '27017:27017'
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: onecrawlrootpass
    volumes:
      - ./crawldb-data:/data/db

  crawler-dashboard:
    container_name: onecrawl-db-dashboard
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
